CompileFlags:
  Add: [--std=c++20, -Wall, -Wextra, -Werror, -O0]
  Compiler: clang

Diagnostics:
  ClangTidy:
    Add: bugprone* clang* google* modernize* performance* readability*  
  UnusedIncludes: Strict

InlayHints:
  Enabled: No
  ParameterNames: No
  DeducedTypes: No
