CompileFlags:
  Add: [-Wall, -Wextra, -Werror, -std=c++2a]
Compiler: clang

Diagnostics:
  ClangTidy:
    Add: bugprone* clang* google* modernize* performance* readability*  
  UnusedIncludes: Strict

InlayHints:
  Enabled: No
  ParameterNames: No
  DeducedTypes: No
